# Generated by Django 5.1.4 on 2025-01-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='bookimages/default.png', upload_to='bookimages'),
        ),
    ]
